name: Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  master_build:
    name: Main Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
      - name: Sanity Check
        run: |
          go vet ./...
          go test -short ./...
